services:
  postgres:
    image: postgres:16-alpine
    container_name: healthcare-postgres
    environment:
      POSTGRES_USER: healthcare
      POSTGRES_PASSWORD: jerry
      POSTGRES_DB: healthcare
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U healthcare -d healthcare" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: healthcare-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
